### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by mehdicopter** [mmmago/cowboyunleashed#1]
Do you think it is possible to have it on AppStore ? Oh and why you do not want to release the code ?

Anyway thank you for your work!

**Comment by mmmago** [comment]
Hello Mehdi, 

To submit it to the appstore, I'd need to have a developper account, which cost 99$/year, plus I'm not sure they would even allow it. I'm not really ready to pay if I'm not 100% sure it would be on the store. 

About the source code, as the dev of [Untamed](https://github.com/Imaginous/Cowboy_Untamed) stated, it might be clever for the sustainability of the hack to not let the source code open. 

Of course, If any dev would like to help on the developpement, I'm open.

Take care !

**Comment by ricardobeat** [comment]
@mmmago all the inner workings are publicly exposed at https://github.com/Imaginous/Cowboy_Untamed/blob/main/IOS.md, what else exactly needs to be protected in the source code?
