### ISSUE TITLE
Motor of C3 and C4 the same?

### ISSUE THREAD

**Issue by heinzgruber** [mmmago/cowboyunleashed#11]
Hi
there are rumors that die C3 (30 Nm) has the same Motor thanthe C4 (45 Nm) and that it would be possible to unleash the full power via a software hack. 

Do you know anything about this?

Thanks

**Comment by mmmago** [comment]
Hello, the motors are actually different in the C3 than the C4. Both are Cowboy custom, but in partnership with different companies. Both can deliver 250W but you can't "upgrade" torque via software.

**Comment by heinzgruber** [comment]
Thanks.
