### ISSUE TITLE
Developer mode on iOS 16

### ISSUE THREAD

**Issue by awalczyk5** [mmmago/cowboyunleashed#12]
Hi,

lastest version 4.2.2 after installing with Sideloadly and trusting the app still require "Developer mode" . Any chance to get around it?

**Comment by mmmago** [comment]
On your phone settings : Privacy & Security > Developper mode > Turn switch on ?

**Comment by awalczyk5** [comment]
Unfortunately "Developer mode" was hidden on my iOS 16.
For anyone having the same issue and those who don't have macOS (Xcode app) here is the solution:
https://www.youtube.com/watch?v=pjOwtVS4jMA

All the best!
