### ISSUE TITLE
AltServer

### ISSUE THREAD

**Issue by jtcurran** [mmmago/cowboyunleashed#13]
Greetings,

I have successfully installed AltServer on my phone and downloaded cowboyunleashed. In my downloads, I see the file and it is using the icon for AltServer, but when I select it all I get is what is in the attached screenshot. As the app is not in the AltServer store, I can't figure out any other way to get it to work. Thoughts?

John
![unleashed - 1](https://user-images.githubusercontent.com/108754742/195156420-0ac33596-c301-484e-aa5c-e759ebd0520c.jpeg)

**Comment by mmmago** [comment]
Hello, you have to click on the arrow on the bottom left and select "Open in altstore".

**Comment by jtcurran** [comment]
Thank you! Success!
