### ISSUE TITLE
Startup power support

### ISSUE THREAD

**Issue by ky1ejs** [mmmago/cowboyunleashed#14]
Hi there! Great job with the project!

I wondered if this app allows me to tweak how much support the motor gives on a standing start (e.g. 0 mph to say 10 mph)?

On the C4 I find it to be a little too weak vs other electric bikes I've tried. Feels like it could give more of a boost there to build your momentum.

**Comment by mmmago** [comment]
Hello ! So sorry for the late reply. I don't think there is a software solution to give a better "push" to the bike, because you're limited with the motor power and torque. You could try tweaking the HIT settings, but that will only adjust when the motor kicks in, not how much.

**Comment by mmmago** [comment]
@ky1ejs The latest bike update should fix your issue :)

**Comment by ky1ejs** [comment]
Yeh! It's like they read my mind! Very happy to see that they've made this update, it's speaks to the exact thing I looking to solve, especially going up hills.
