### ISSUE TITLE
Any plans on releasing the source code?

### ISSUE THREAD

**Issue by TimBroddin** [mmmago/cowboyunleashed#17]
Hey,

First & foremost: thank you so much for developing this app. With recent rumors about Cowboy going out of business, having a backup solution in case they do is wonderful 🙏

I was wondering if you have plans to release the source code. This would make it easier for people who have a developer certificate to install it permanently, and you can maybe gather some contributors for this project.

**Comment by mmmago** [comment]
Hello, 

I'm waiting to see how easily Apple will allow sideloading on iOS 17, but I may make the app open source at this moment, so around september '23.
