### ISSUE TITLE
Horizontal scrolling in Home/Write/Read tabs

### ISSUE THREAD

**Issue by Jaaap** [mmmago/cowboyunleashed#18]
Just a small UI bug:
In the first 3 tabs (Home/Write/Read) the interface allows some horizontal scrolling even though the content fits the viewport.

iPhone 12 / iOS 16.4 / Unleashed 4.3

Suggested behavior: no horizontal scrolling is possible at all

**Comment by mmmago** [comment]
Hello Jaaap, thanks for your feedback.

~~Would you mind sharing a video recording of the issue ?~~

Fixed ! Will put that in next update.
