### ISSUE TITLE
Small Textual / Spelling / Grammar changes

### ISSUE THREAD

**Issue by Jaaap** [mmmago/cowboyunleashed#19]
Resetting Printed Circuit Board may resolve connexion problems with your bike
=> conne**cti**on

Please make sure that the Cowboy app is not running in background
=> in **the** background

Disabling speed limit will allow**s** your bike going up to
==> will allow

Please note that disabling it in Unleashed for the C2/C3/C4 will took over the Cowboy app switch
==> will **take** over

the blinking red light on the battery when you brake might be not sensitive enough
==> might not be

You can set a more sensitive value to make sure everyone see when you brake
==> see**s** / can see

**Comment by mmmago** [comment]
Thanks a lot, I'm not native english speaker. Will definitly correct that in the next update !
