### ISSUE TITLE
Video tutorial

### ISSUE THREAD

**Issue by Mrpoulpe** [mmmago/cowboyunleashed#2]
Video tutorial would it be possible to have a video tutorial on the installation and use of the application? When you use your app to unlock your bike, can you still use the Cowboy app to see the route and speed? Thank you again for your work.

**Comment by mmmago** [comment]
Hello,

I will edit the description for an installation tutorial.

The app is only used to apply the settings. You can use it with the main cowboy app, just make sure it is not running in the background when you try to apply settings.

**Comment by Mrpoulpe** [comment]
Thank you for your quick response. I will try your application as soon as I am no longer blocked by Apple with the number of devices in the developer account, which prevents me from installing altserver on my iPhone.
