### ISSUE TITLE
iOS 17 to Support App Sideloading

### ISSUE THREAD

**Issue by Jaaap** [mmmago/cowboyunleashed#21]
Will iOS 17 make it easier to load Unleased on your iPhone?
I have lots of trouble using Sideloadly to load it atm.
This would potentially be a very welcome change.

https://www.macrumors.com/2023/04/17/app-sideloading-support-coming-ios-17/

**Comment by mmmago** [comment]
I definitly hope so ! It's about time. In the meantime, take a look at [https://usescarlet.com/](Scarlett).
