### ISSUE TITLE
App won‘t open at all

### ISSUE THREAD

**Issue by mehri92** [mmmago/cowboyunleashed#22]
Hey! I've been encountering a recurring problem with the Unleashed app that I sideloaded using Sideloadly. Initially, it works flawlessly for a few days, but then it refuses to open unless I remove and sideload it again. A system message pops up, saying "Unleashed is not available anymore." 

I’ve been observing this issue for 6 weeks now and tried both staying on my iOS version and updating after the bug reappeared. 

I'm curious to know if this is a common occurrence, or if there's any way to prevent this inconvenience. It can be quite frustrating, especially when I find myself in situations where I don't have access to my PC for resideloading. Any suggestions or insights would be greatly appreciated. Thanks in advance!

![IMG_8734](https://github.com/mmmago/cowboyunleashed/assets/99403348/508be3fa-50e4-460a-8aaa-d0466c68bca4)

**Comment by mmmago** [comment]
Hello, please read https://github.com/mmmago/cowboyunleashed#download--installation.

iOS 17 should allow sideloading in Europe before the end of the year.
