### ISSUE TITLE
Can we somehow circumvent the loss of warranty?

### ISSUE THREAD

**Issue by tonysprenk** [mmmago/cowboyunleashed#24]
Is it possible to wipe the ride data off the bike before claiming warranty after using unleashed? Or is that data stored in the cloud? Thanks for the great app btw!

**Comment by mmmago** [comment]
Not possible, the data is stored on cowboy servers.

**Comment by tonysprenk** [comment]
What if I never use the official app after initial registration?

**Comment by mmmago** [comment]
You can try, but the data is also stored on the bike itself (and can't be wiped)
