### ISSUE TITLE
AltStore PAL for iOS in EU

### ISSUE THREAD

**Issue by Jaaap** [mmmago/cowboyunleashed#26]
Is it possible to add Cowboy Unleashed to AltStore PAL for iOS?
See https://altstore.io/ and https://rileytestut.com/blog/2024/04/17/introducing-altstore-pal/

**Comment by mmmago** [comment]
Hey ! I'm keeping an eye on everything related to sideloading in EU and will try to implement a solution to sideload the app as soon as I can :)

**Comment by Jaaap** [comment]
Since AltStore PAL is now free to use, could you say a few words about how hard it would be to get Unleashed into AltStore PAL?

**Comment by Jaaap** [comment]
It appears that all you (the developer) need to do is make a "source".
https://faq.altstore.io/developers/make-a-source

**Comment by mmmago** [comment]
Hey @Jaaap,

Late to this, but as using a Altstore PAL repo still implies Apple and going through the Apple for Notarization process, I won't be able to do it. See [distribute with Altstore PAL](https://faq.altstore.io/developers/distribute-with-altstore-pal)
