### ISSUE TITLE
Provisioning profile missing

### ISSUE THREAD

**Issue by SeegersInVegas** [mmmago/cowboyunleashed#4]
Hi, 
when trying the "Normal Installation" using Sideloadly, your .IPA is missing a valid provisioning profile.

![grafik](https://user-images.githubusercontent.com/56734521/168422718-b551493e-e458-4dcc-b408-addfcb933f30.png)

Greetz

**Comment by mmmago** [comment]
Hello, sorry for late anwer. Last version of sideloadly should fix the issue.
