### ISSUE TITLE
installable file

### ISSUE THREAD

**Issue by mrkrabs6974** [mmmago/cowboyunleashed#8]
can you provide an installable imazing file thx.

**Comment by mmmago** [comment]
What kind of file is it ? Only installable file is findable [here](https://github.com/mmmago/cowboyunleashed/releases).

**Comment by mrkrabs6974** [comment]
I found it and it’s working great 👍 thx
Installed with sideloady

Sent from my iPhone

**Comment by mrkrabs6974** [comment]
The app works great 👍 
C2 with Cowboy App version 3.4.0 and  FW 4.14.8 

iPhone 12 Pro Max with iOS 15.6
